### PR TITLE
[utility] gulp fetch

### PR DESCRIPTION
**Pull request by jmlopez-rod**
I'm adding this utility so that we can see if we need to add or remove rules from ESLint as well as linking rules to the ones provided from TSLint. For instance, this is what I can see right now after running the command:

```bash
$ gulp fetch
[10:56:01] Using gulpfile ~/Github/tslint-eslint-rules/gulpfile.js
[10:56:01] Starting 'lint'...
[10:56:04] Finished 'lint' after 2.57 s
[10:56:04] Starting 'build'...
[10:56:06] Finished 'build' after 2.13 s
[10:56:06] Starting 'fetch'...
[10:56:06] Finished 'fetch' after 34 ms
Missing TSLint rules (http://palantir.github.io/tslint/rules):
- adjacent-overload-signatures
- align
- array-type
- ban
- class-name
- comment-format
- cyclomatic-complexity
- eofline
- file-header
- interface-name
- jsdoc-format
- label-position
- label-undefined
- max-file-line-count
- max-line-length
- member-access
- member-ordering
- no-angle-bracket-type-assertion
- no-bitwise
- no-consecutive-blank-lines
- no-construct
- no-constructor-vars
- no-default-export
- no-for-in-array
- no-inferrable-types
- no-internal-module
- no-mergeable-namespace
- no-null-keyword
- no-reference
- no-require-imports
- no-string-literal
- no-unsafe-finally
- no-unused-new
- no-use-before-declare
- no-var-requires
- object-literal-key-quotes
- object-literal-shorthand
- object-literal-sort-keys
- one-line
- one-variable-per-declaration
- only-arrow-functions
- ordered-imports
- prefer-for-of
- quotemark
- restrict-plus-operands
- semicolon
- use-strict
- whitespace 

Missing ESLint rules (http://eslint.org/docs/rules):
- class-methods-use-this
- func-call-spacing
- line-comment-position
- lines-around-directive
- max-lines
- multiline-ternary
- no-bitwise
- no-global-assign
- no-mixed-operators
- no-plusplus
- no-prototype-builtins
- no-restricted-globals
- no-restricted-properties
- no-tabs
- no-template-curly-in-string
- no-unsafe-finally
- no-unsafe-negation
- no-useless-computed-key
- no-useless-rename
- object-curly-newline
- object-property-newline
- prefer-numeric-literals
- rest-spread-spacing
- sort-keys
- symbol-description
- unicode-bom
```

Note that not all TSLint rules will apply, for that I have provided a json file where we can exclude them. I have placed the most obvious ones that I can see.

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
Just a thought, perhaps I can modify the functions so that they can be used on release. That is, when you are about to release this can also be ran with the tests to see if you have the most up to date README with all the rules. If it fails then we can make the update and mention on the README the most recent version of TSLint and ESLint.

**Comment by buzinas** [comment]
Although I like the idea, I think it would be better to manually do this.

**Comment by jmlopez-rod** [comment]
Yeah, just a thought, I'll try to update the rest of the readme with the new stuff that showed up  sometime next week.

**Comment by jmlopez-rod** [comment]
Also, just to clarify, the task only prints out information, it's not actually syncing, the name is bad and I should feel bad. Any good names for the task?

**Pull request merged**
