### PR TITLE
Revert "[gulp] using typescript to maintain the gulpfile"

### PR DESCRIPTION
**Pull request by buzinas**
Reverts buzinas/tslint-eslint-rules#112

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
Did something happen with the modification using typescript for the gulpfile?

**Comment by buzinas** [comment]
The build time increased by almost one minute, and also I didn't like the on-the-fly transpilation using `eval`, nor the `class` and `decorators` for the gulp-task.

I'm taking some of the work you did in the other PR and I'll be merging it in a few minutes.

**Comment by jmlopez-rod** [comment]
Sounds good. Yeah, we should get the bug fixes at least. Too bad things got slower :(.

**Comment by jmlopez-rod** [comment]
Would it make any difference if we use [ts-node](https://github.com/TypeStrong/ts-node)? This way we won't need to have `gulpfile.js` at all. We could skip the gulpclass stuff and just write the gulp file but using typescript. I'll try again in another branch. How did you measure the build time? I assume it wasn't this:

```
$ gulp build
[22:29:26] Using gulpfile ~/Github/tslint-eslint-rules/gulpfile.js
[22:29:26] Starting 'lint'...
[22:29:28] Finished 'lint' after 2.61 s
[22:29:28] Starting 'build'...
[22:29:30] Finished 'build' after 2 s
```

**Comment by buzinas** [comment]
In fact, I was talking about the *CI time.

About the gulpfile, I think I'm happy with it in Javascript. If at least TypeScript had something similar to the `babel-register`, we could probably use it.

**Comment by jmlopez-rod** [comment]
I see. darn, in that case then ts-node probably won't make a difference. Perhaps at a later time. Let me know if you need some help incorporating the changes to fix the async problems.

**Comment by buzinas** [comment]
@jmlopez-rod I tried to incorporate the changes, please feel free to fix them if I forgot anything.

**Pull request merged**
