### PR TITLE
[docs] update README tables and remove ter-indent

### PR DESCRIPTION
**Pull request by raspo**
I was going through a merge of some of my own eslint rules with TSlint ones and I noticed that a few rules listed as not available on the README have actually been added to TSlint.

- [no-duplicate-imports](https://palantir.github.io/tslint/rules/no-duplicate-imports/)
- [prefer-template](https://palantir.github.io/tslint/rules/prefer-template/)
- [space-before-function-paren](https://palantir.github.io/tslint/rules/space-before-function-paren/)
- [indent](https://palantir.github.io/tslint/rules/indent/) (replacing `ter-indent`)

When I ran `gulp readme` the build was failing and the only way I found to fix it was to remove `ter-indent` from this repo. I'm not sure if that's the correct thing to do at this time though.

Let me know how can I improve this PR.

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
Any reason why `ter-indent` got deleted? This rule is different from the tslint indent. Notice that they say:

```
 it will not fix invalid whitespace sizes.
```

ter-indent does since this code was ported from eslint indent.

**Comment by raspo** [comment]
Oh, I see.
Any ways we can have both `indent` and `ter-indent`?

I mentioned that I had to remove `ter-indent` because it would break the `gulp readme` build.

**Comment by jmlopez-rod** [comment]
Yeah, we can have both, that's why all the rules created in this repo start with `ter` so that there are no conflicts. In the future tslint might start taking the same names as eslint and yet be different from what eslint does. That's why we give the prefix. In the documentation we just point that out so that users can decide what rules to use.

**Comment by jmlopez-rod** [comment]
By the way, please don't edit the README manually. Instead modify `tslint_eslint_rules.json` and then run `gulp readme` to update the readme file. See the CONTRIBUTING file in the `Updating the README tables` section.

**Comment by jmlopez-rod** [comment]
Closing since `ter-indent` is completely different from the TSLint `indent` rule.

**Pull request closed without merging**
