### PR TITLE
Fix typescript build errors

### PR DESCRIPTION
**Pull request by mnmtanish**
- Use the getSkipEndFromStart method
 - Fix visitArrowFunction function usage

### CODE REVIEW

**Comment by mnmtanish** [comment]
The build is failing on Travis CI for Node v0.10 because `Set` is not available in Node v0.10

**Comment by jmlopez-rod** [comment]
@blakeembrey @buzinas This seems to be a breaking change for node 0.10 coming from tslint since the `no-shadow-variable` got recent updates:

https://github.com/palantir/tslint/blob/master/src/rules/noShadowedVariableRule.ts#L45

Is it good time to stop supporting node 0.10 since tslint doesn't?

**Comment by blakeembrey** [comment]
Seems reasonable to me now, 0.10 is EOL. The versioning is pretty tied to TSLint too.

**Comment by jmlopez-rod** [comment]
Merging this to make it compatible with the latest typescript. Will drop support of node 0.10 shortly after this is merged since this is what's making the CI fail.

**Pull request merged**
