### PR TITLE
[fix] handle-callback-err (nested property access expression)

### PR DESCRIPTION
**Pull request by jmlopez-rod**

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
@blakeembrey Can you check the new tests to see if I may be missing something?

**Comment by blakeembrey** [comment]
Nice, LGTM 👍 I see the issue now too! 😄

**Comment by jmlopez-rod** [comment]
Awesome, i'm releasing.

**Comment by jmlopez-rod** [comment]
@blakeembrey And it's released, hopefully your builds are ok now.

**Comment by blakeembrey** [comment]
@jmlopez-rod LGTM 👍

**Pull request merged**
