### PR TITLE
[feat] Add options for object-curly-spacing rule

### PR DESCRIPTION
**Pull request by peterjwest**
My first time working with linting rules, so I hope I've done it right!

Also I had to amend some of the commented out tests, can someone please check they are correct?

### CODE REVIEW

**Comment by peterjwest** [comment]
The PR failed because NPM timed out 😞

**Comment by jmlopez-rod** [comment]
Nice, thanks for the contribution.

**Comment by jmlopez-rod** [comment]
Yeah, I'm switching us to yarn, just need to find some time this weekend.

**Comment by peterjwest** [comment]
Would it help if I made the yarn PR?

**Comment by jmlopez-rod** [comment]
The two others checks passed so lets go with it.

**Comment by peterjwest** [comment]
Thanks! 😁

**Pull request merged**
