### PR TITLE
 [bug] fixed ter-newline-after-var (closes #294)

### LINKED ISSUE #294: Rule "newline-after-var" incorrectly fixing code and within try catch block
I've enabled the "newline-after-var" rule, however when fixing it doesn't seem to maintain the existing indentation. For example this code:

```
   try {

      const result = await request.send();

   } catch (err) {

      throw new Error(err);

   }
```

Is incorrectly changed to:
```
   try {

      const result = await request.send();

   } 
catch (err) {

      throw new Error(err);

   }
```

As it's the end of a try catch it shouldn't be fixing this, and secondly the newline it adds has no indentation.

Thanks

### PR DESCRIPTION
**Pull request by webschik**

### CODE REVIEW

**Comment by jhdevuk** [comment]
@webschik This is no longer incorrectly changing try/catch blocks but the indentation issue for the fixer is still broken:
```
class Example {

   constructor() {

      const test = 'abc123';
      this.runMethod();

   }

}

```

Is changed to:

```
class Example {

   constructor() {

      const test = 'abc123';
      
this.runMethod();

   }

}
```

Thanks for the speedy response though! Much appreciated.

**Comment by webschik** [comment]
@jhdevuk, thanks! I've added your test case and fixed the bug

**Comment by jhdevuk** [comment]
@webschik Brilliant, tested on my code base, all works as expected. Thanks again

**Comment by webschik** [comment]
@buzinas , your turn ;)

**Pull request merged**
