### PR TITLE
[feat] Add auto fix feature to object-curly-spacing rule

### PR DESCRIPTION
**Pull request by aksyonov**
With this you can run `tslint` with `--fix` option and all curly braces paddings will be fixed.

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
Thank you so much for the first fixer ever in this repo. I'll try to get the other PRs merged soon so that we can see where the CI is complaining. Looking forward to creating the fixers for the other rules now that you are showing the way to creating tests for them.

**Comment by jmlopez-rod** [comment]
@aksyonov I have merged https://github.com/buzinas/tslint-eslint-rules/pull/173 which fixes the issues with the most recent typescript. Could you merge master to see if the PR is ok?

**Comment by aksyonov** [comment]
@jmlopez-rod I rebased my branch, ci should be ok now.

**Comment by jmlopez-rod** [comment]
That's awesome, all tests are passing. Merging for now, I'll try to do a release once I finish with some of the other issues this weekend. Thanks again.

**Comment by aksyonov** [comment]
Thank you too, looking forward for a new release.

**Pull request merged**
