### PR TITLE
[gulp] using typescript to maintain the gulpfile

### PR DESCRIPTION
**Pull request by jmlopez-rod**
With this change now all the code will be managed in typescript. Since the build task targets all the typescript files in the `src` directory this means that the gulpfile will be also linted and thus kept to the same standards as the rest of the code.

### CODE REVIEW

**Comment by buzinas** [comment]
Thanks for the PR.

Can you please resolve the conflicts so I can merge it?

**Comment by buzinas** [comment]
Let me know if it's ready for merging.

**Comment by jmlopez-rod** [comment]
Its not yet ready, there is still a bug in there (async process when generating the readme). I thought I fixed it in the last commit but it wasn't the case. I'll let you know when its done.

**Comment by buzinas** [comment]
OK, thanks!

**Comment by jmlopez-rod** [comment]
Ok, done. Things should be goo given that all the checks passed. My only problem in my IDE is that it highlights `Promise` since it cannot find it. On the build process everything is fine because we have

```
.src([
        Gulpfile.SRC_FOLDER,
        Gulpfile.DEF_FOLDER,
        'node_modules/typescript/lib/lib.es6.d.ts'
      ])
```

That is, typescript picks up the definition of `Promise` from ` 'node_modules/typescript/lib/lib.es6.d.ts'` and thus it passes. Any idea how to make the IDE aware of it?

**Pull request merged**
