### PR TITLE
[feat] ter-indent (closes #74)

### LINKED ISSUE #74: indent with "4" or "2" spaces
Hi, Thanks for this TSLINT extension. That would be nice if we replace the indent method with the [eslint one](http://eslint.org/docs/rules/indent).

So we could set the number of spaces, like:

`{indent: [true, 2]}`
`{indent: [true, 4]}`
`{indent: [true, "tab"]}`

What do you think?

Thanks

### PR DESCRIPTION
**Pull request by jmlopez-rod**
This is a direct port of eslint `indent` rule. As such, it only seems to cover the basics of es6, that is, there is nothing on decorators.

A few modifications were done to the test helpers to facilitate creating tests for the rule.

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
@buzinas Seems like my last attempt to get rid of the error did not work. Do you have any suggestions on how bring the assign function? Before merging I'd like to add support for decorators so lets wait on this for a bit. I also need to update the docs.

**Comment by jmlopez-rod** [comment]
@buzinas I think I'm done with my changes. I have updated the README file and the documentation for the rule explaining the differences to the `indent` rule provided by TSLint. Let me know if you notice something that should be changed. Also, could you give me a heads up on the next release, I'd like to get one more pull request in.

**Comment by leocaseiro** [comment]
Thank you so much @jmlopez-rod! |
LGTM!

Hi, @buzinas 

It seems pretty good. It's working for me here.

Are you planning to accept this PR?

Thanks

**Comment by buzinas** [comment]
Hi @leocaseiro and @jmlopez-rod, thanks!
Sorry for the delay, I was really busy the last few weeks.

I'll add @jmlopez-rod as one of the npm contributors, so he can do releases as well.

**Comment by leocaseiro** [comment]
Thank you @buzinas.

No worries, I understand.

Cool!

**Comment by mrmlnc** [comment]
A little clarification: whether there are any plans to add support for `CallExpression`? 🌮

**Comment by jmlopez-rod** [comment]
@mrmlnc you bet, could you please open up an issue and point out missing features on the rule that may not yet be available on eslint? I just look at the tests and it seems that we are not covering parameter indentation for methods. I'd like to get a collection of missing options so that I may start adding them.

**Pull request merged**
