### PR TITLE
[docs] linked no-new ESLint rule with no-unused-expression TSLint rule

### LINKED ISSUE #249: Bad reference to tslint rule 'no-unused-new'
TSLint removed rule `no-unused-new` and all its functionality was included into the `no-unused-expression`  rule ( palantir/tslint#2269 ). Table should be updated.

### PR DESCRIPTION
**Pull request by trivikr**
Closes #249

### CODE REVIEW

**Comment by trivikr** [comment]
Travis CI build [failure](https://travis-ci.org/buzinas/tslint-eslint-rules/jobs/277822044) in terIndentRule.ts is unrelated to this code change

**Comment by jmlopez-rod** [comment]
I'm a bit confused by this change, doesn't the `no-unused-new` match the eslint `no-new` rule better?

https://eslint.org/docs/rules/no-new

https://palantir.github.io/tslint/rules/no-unused-new/

vs

https://palantir.github.io/tslint/rules/no-unused-expression/

**Comment by trivikr** [comment]
Hi @jmlopez-rod I've fetched latest upstream and rebased this branch with upstream/master
The issue is described in #249

**Comment by jmlopez-rod** [comment]
Ah, weird that they did not remove or updated the doc page to mention that it was deprecated.

**Comment by trivikr** [comment]
@jmlopez-rod I'd made code change to remove outdated documentation in TSLint at https://github.com/palantir/tslint/pull/3230
They've to bring up generated docs from **master** to **gh-pages** in https://github.com/palantir/tslint/issues/3185 which is a manual bug

**Pull request merged**
