### PR TITLE
Switch to yarn and update documentation

### PR DESCRIPTION
**Pull request by peterjwest**
Converted lock file using `synp` package.

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
You'll also need to add this to `.travis.yml`:

```
language: node_js

node_js:
  - 8
  - 6
  - 4

branches:
  only:
    - master

cache: yarn

before_install:
  - echo "//registry.npmjs.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn run test
```

**Comment by jmlopez-rod** [comment]
If the build passes with it then I'll go ahead and merge it. This will make it so that travis uses yarn all the way.

**Comment by peterjwest** [comment]
If you look at the build, it already used yarn to install, and `yarn test` to run the tests.

The only thing I think it needs is
`cache: yarn`

and 
```
branches:
  only:
    - master
```
if you want it

**Comment by peterjwest** [comment]
Any response on this?

**Comment by peterjwest** [comment]
@jmlopez-rod Can you take a look at this again?

**Pull request merged**
