### PR TITLE
[feat] added array-bracket-spacing rule (closes #57)

### LINKED ISSUE #57: Create array-bracket-spacing rule
We're gonna need this to our projects, and tslint can also benefits from this (https://github.com/palantir/tslint/issues/1045.).

### PR DESCRIPTION
**Pull request by nfriend**

### CODE REVIEW

**Comment by buzinas** [comment]
@nfriend Thanks for the PR!

I have one question, though. About [the extra options](http://eslint.org/docs/rules/array-bracket-spacing#exceptions):  did you choose to don't support it by design or didn't you see that they exist?

> The following exceptions are available:
> 
> -     singleValue sets the spacing of a single value inside of square brackets of an array.
> -     objectsInArrays sets the spacings between the curly braces and square brackets of object literals that are the first or last element in an array.
> -     arraysInArrays sets the spacing between the square brackets of array literals that are the first or last element in an array.

**Comment by nfriend** [comment]
Sorry about that - I didn't see that those extra options exists.  I thought "always" and "never" were the only configurations for this rule.  I'll add the extra options and submit a new PR.

**Comment by nfriend** [comment]
@buzinas Extra options have been added.  I also restructured the implementation to be closer to the implementation of the [eslint rule](https://github.com/eslint/eslint/blob/master/lib/rules/array-bracket-spacing.js).

**Comment by buzinas** [comment]
Thanks, @nfriend! You're doing an awesome job, and your help is invaluable!

**Pull request merged**
