### PR TITLE
tsconfig.json => tslint.json

### PR DESCRIPTION
**Pull request by tkrotoff**
You meant `tslint.json` right?

### CODE REVIEW

**Comment by buzinas** [comment]
@tkrotoff sure, thanks :)

**Comment by buzinas** [comment]
Your commit should be renamed for something like:
```
[docs] fixed README.md tsconfig.json => tslint.json
```

**Comment by tkrotoff** [comment]
@buzinas done

**Comment by buzinas** [comment]
Thanks @tkrotoff!

**Pull request merged**
