### PR TITLE
[bug] fix null warning in valid-jsdoc

### LINKED ISSUE #9: Create rule no-dupe-keys

### LINKED ISSUE #238: Warning: Cannot read property 'name' of null - caused by valid-jsdoc rule
- `tslint 5.4.3`
- `tslint-eslint-rules 4.1.1`

TSlint config:

```json
"valid-jsdoc": [true, {
  "requireReturn": false,
  "requireReturnType": false
}],
```

Code:

```ts
class MyPage {
  /**
   * Navigate to the page
   * @returns a promise for the browser's navigation
   */
  public async navigateTo() { }
}
```

Getting this warning:

```
Warning: Cannot read property 'name' of null
```

### PR DESCRIPTION
**Pull request by Merott**
Closes #238 

This fixes the issue, and adds a test for it. The only problem is, the test suite won't actually fail on warnings. It displays the warning, but it won't fail:

image

Let me know if there is anything I must do to make the test suite fail on the warning.

### CODE REVIEW

**Comment by buzinas** [comment]
LGTM, will wait for @jmlopez-rod input

**Comment by Merott** [comment]
It appears that TSLint is swallowing the error and logging it as a warning. I couldn't find a way to force it not to.  Perhaps a workaround (<sup>an ugly one</sup>) would be to search the output with a regex post-`test`?

**Comment by jmlopez-rod** [comment]
@Merott I wonder if they have some flag to disable this behavior, at least for development purposes.

**Comment by jmlopez-rod** [comment]
I guess they don't:

```ts
    private applyRule(rule: IRule, sourceFile: ts.SourceFile): RuleFailure[] {
        try {
            if (this.program !== undefined && isTypedRule(rule)) {
                return rule.applyWithProgram(sourceFile, this.program);
            } else {
                return rule.apply(sourceFile);
            }
        } catch (error) {
            if (isError(error) && error.stack !== undefined) {
                showWarningOnce(error.stack);
            } else {
                showWarningOnce(String(error));
            }
            return [];
        }
    }
```

**Comment by sanex3339** [comment]
When i can expect this fix?

**Pull request merged**
