### PR TITLE
[typescript] updating to 2.6 and latest tslint

### PR DESCRIPTION
**Pull request by jmlopez-rod**

### CODE REVIEW

**Comment by jmlopez-rod** [comment]
Doing the update to 2.7 will take some time since it points out more errors. I'll be doing a release of this soon and go over all the other PRs.

**Comment by jmlopez-rod** [comment]
@buzinas can we make travis use npm > 5.0? it would be useful to have the same package-lock.json

**Comment by buzinas** [comment]
> @buzinas can we make travis use npm > 5.0? it would be useful to have the same package-lock.json

How about switching to yarn?

**Comment by jmlopez-rod** [comment]
I have conflicts about yarn. I tried it since I really wanted to "flat" install so that we don't get repeated packages but somehow it didn't work. I suppose we could try it. Is that what tslint is using? Lets do it when we update everything to be compatible with typescript 2.7. Sorry I haven't had time to work on this.

**Comment by jmlopez-rod** [comment]
IT PASSED!!!

**Pull request merged**
